segmentio/golines

_fixtures/comments.go
_fixtures/comments__exp.go
shortener.go

As reported in https://github.com/segmentio/golines/issues/9, shortening a comment containing a word that's longer than the configured maximum length can lead to an extraneous, blank comment line in the output. This change fixes this by checking whether there are words to emit before outputting a new comment line.

Fix comment shortening with long words

---

_fixtures/comments.go
_fixtures/comments__exp.go
_fixtures/end_to_end__exp.go
shortener.go

This change fixes a small bug in comment handling that can cause shortened comments to be slightly longer than the configured maximum length.

Fix comment shortening

---

_fixtures/struct_tags.go
_fixtures/struct_tags__exp.go
go.mod
go.sum
shortener.go
tags.go

This change includes several fixes and improvements to the `golines` struct tag alignment logic:
1. Use [fatih/structtag](https://github.com/fatih/structtag) for parsing out tag keys instead of a naive regular expression. The former handles embedded colons and other edge cases a lot better.
2. Perform tag alignment for structs defined inside functions
3. Try to improve tag alignment in case of embedded structs
Note that (3) is still best-effort. See the `struct_tags` fixture for examples that are handled and not handled currently.

Misc. struct tag alignment improvements

---

README.md

This change updates the VSCode integration instructions in the README to work with the latest version. See https://github.com/segmentio/golines/issues/20 for details.

Fix VSCode instructions

---

_fixtures/binary_operators.go
_fixtures/binary_operators__exp.go
shortener.go

I found a problem that if we have a long and complex expression, then golines will add a new line only before last operand.
So if you have a code like this:
```
if getBooool1() || getBooool2() || getBooool3() || getBooool4() || getBooool5() || getBooool6() || getBooool7() {
return "Hey"
}
```
it will become
```
if getBooool1() || getBooool2() || getBooool3() || getBooool4() || getBooool5() || getBooool6() ||
getBooool7() {
return "Hey"
}
```
My fix is pretty simple. The result will look like this
```
if getBooool1() || getBooool2() || getBooool3() || getBooool4() || getBooool5() ||
getBooool6() ||
getBooool7() {
return "Hey"
}
```
It is not perfect. I would like to see something like this:
```
if getBooool1() || getBooool2() || getBooool3() || getBooool4() || getBooool5() ||
getBooool6() …
```

Fix formatting for very long binary expressions

---

.circleci/config.yml
README.md
go.mod
main.go

This change updates the project minimum go version to 1.17. It also fixes the installation instructions in the README and bumps the version to `0.0.6`.

Update go to 1.17

---

README.md
_fixtures/inline_interface.go
_fixtures/inline_interface__exp.go
annotation.go
main.go
shortener.go

This change fixes the issue described in https://github.com/segmentio/golines/issues/40. It also improves the documentation around custom formatter interfaces as discussed in https://github.com/segmentio/golines/issues/44.
Testing completed successfully via adding a new fixture, verifying that the shortened version looked as expected.

Fix shortening of inline interface definitions inside function declarations

---

_fixtures/comments.go
_fixtures/comments__exp.go
shortener.go

For a comment containing multiple contiguous long lines, the current
behavior is to preserve the line breaks in between them.
$ cat x.go
package main
// This comment contains multiple contiguous lines which are greater than the target maximum line length.
// The expected result is a sequence of shortened (reflown) lines without preserving the position of line breaks.
$ golines --shorten-comments x.go
package main
// This comment contains multiple contiguous lines which are greater than the target maximum line
// length.
// The expected result is a sequence of shortened (reflown) lines without preserving the position of
// line breaks.
The modified behavior is a sequence of shortened (reflown) lines without
preserving the position of line breaks.
$ golines --shorten-comments x.go
package …

Improve comment reflow

---

diff.go

The embedded python script currently adds color codes even if the user
redirects output to a file (e.g., `golines --dry-run file.go > diff.txt`).
This updated version uses `isatty` to prevent that.

Don't add colors unless output goes to a terminal

---

README.md

This change updates the README to reflect the Python dependency removal done in https://github.com/segmentio/golines/pull/51.

Remove python references from README

---

diff.go

This is a fix for: https://github.com/segmentio/golines/issues/54
I believe this is the preferred approach to ensure cross-platform compatibility. Things are working for me now in Windows but I don't have a way of verifying things in another OS.

Change syscall to os in terminal check for Windows compatibility

---

go.mod
go.sum

The project build failed under go 1.18, it needs to upgrade `golang.org/x/sys` to newer version.

fix(gomod): upgrade x/sys for go1.18

---

.pre-commit-hooks.yaml

Adds [pre-commit](https://pre-commit.com/) hook config, to be able to run it as a git hook and automatically sort all the long lines before commit.

feat: adds pre-commit hook config

---

graph_generated.go

This change updates the graph generation code in `golines` so that dot files generated by the `--dot-file` option properly show generic type parameters.
Testing completed via running `golines ./_fixtures/generics.go --dot-file=out.dot` and visualizing the resulting graph:

Update graph generation code

---

README.md

This change updates the README to avoid confusion around installation errors for golang versions < 1.18.

Update README with version-specific installation instructions

---

main.go

When the content of a file is unchanged after shortening, it is no
longer rewritten to its source. This prevents file modification times
from changing when no modification occurs; that helps build tools like
make to be more efficient.

Skip writing files with unchanged content

---

tags.go

Before
```go
type Diacritics struct {
A string `foo:"ä" json:"a"`
E string `foo:"e"  json:"e"`
I string `foo:"ï" json:"i"`
O string `foo:"o"  json:"o"`
U string `foo:"ü" json:"u"`
}
```
After
```go
type Diacritics struct {
A string `foo:"ä" json:"a"`
E string `foo:"e" json:"e"`
I string `foo:"ï" json:"i"`
O string `foo:"o" json:"o"`
U string `foo:"ü" json:"u"`
}
```

Fix len on multi-byte characters

---

_fixtures/struct_tags.go
_fixtures/struct_tags__exp.go
main.go
tags.go

This change updates the fixtures to cover https://github.com/segmentio/golines/pull/78. It also bumps the version to cover the changes made in the former change as well as https://github.com/segmentio/golines/pull/77.

Update fixtures and bump version

---

README.md

This change tweaks the README to reflect that golang 1.19 has been released.

Update README to reflect 1.19

---

.goreleaser.yaml
main.go

Hardcoded version numbers are easy to forget to update.

Fix version formatting

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

From the buildkite-agent-golang-1.21 image with golang version 0.12.1 in it:
```
/usr/local/bin/golines --version
/usr/local/bin/golines: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/golines)
/usr/local/bin/golines: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/golines)
```

build: build and release on ubuntu-20.04 for older glibc versions

---

README.md

Tried following to goland instructions and it was unusable as-is because golines is triggered constantly, causing formatting changes mid-type and removing whitespace right after you add it, before you had an opportunity to start typing on a line.
Unchecking a specific checkbox that is checked by default fixes this issue.

Updated REAME instructions for goland usage

---

.pre-commit-hooks.yaml

Using `pass_filenames: true` (the default) is faster than `golines -w .`, because it runs `golines`on only the files that have changed.

feat: fix pre-commit config to use pass_filenames

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
.golangci.yml
graph.go
main.go
shortener.go
tags.go

Versions have been broadly updated but releases are still being generated with the oldest supported Go version, not the latest.

Update GitHub Actions workflows
